### ISSUE TITLE
not working with jquery 3.11

### ISSUE THREAD

**Issue by saqueib** [taras-d/images-grid#7]
I really liked this 👍  but unfortunately, it's not working with jquery 3.11, I cant downgrade since another functionality depends on it. 

Giving me this error.

```
Uncaught TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (jquery-3.1.1.js:9793)
    at jQuery.fn.init (jquery-3.1.1.js:3005)
    at jQuery (jquery-3.1.1.js:98)
    at ImagesGrid.renderGridItem (images-grid.js:174)
    at ImagesGrid.renderGridItems (images-grid.js:141)
    at ImagesGrid.init (images-grid.js:89)
    at new ImagesGrid (images-grid.js:83)
    at HTMLDivElement.<anonymous> (images-grid.js:16)
    at Function.each (jquery-3.1.1.js:368)
    at jQuery.fn.init.each (jquery-3.1.1.js:157)
jQuery.fn.load @ jquery-3.1.1.js:9793
jQuery.fn.init @ jquery-3.1.1.js:3005
jQuery @ jquery-3.1.1.js:98
ImagesGrid.renderGridItem @ images-grid.js:174
ImagesGrid.renderGridItems @ images-grid.js:141
ImagesGrid.init @ images-grid.js:89
ImagesGrid @ images-grid.js:83
(anonymous) @ images-grid.js:16
each @ jquery-3.1.1.js:368
each @ jquery-3.1.1.js:157
$.fn.imagesGrid @ images-grid.js:10
(anonymous) @ index.html:36
```

Please help

**Comment by taras-d** [comment]
Fixed
